// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0zwIyP11BrgH7m9Ul7ZnlSdW9H6dTxZs',
    appId: '1:1040087440308:web:c30fa3123a6c6989caf0e1',
    messagingSenderId: '1040087440308',
    projectId: 'tuna-8c766',
    authDomain: 'tuna-8c766.firebaseapp.com',
    databaseURL: 'https://tuna-8c766-default-rtdb.firebaseio.com',
    storageBucket: 'tuna-8c766.appspot.com',
    measurementId: 'G-H1S16LWCG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABpi7nkCd0Vmar6Vh70wn03QtvP0YOU34',
    appId: '1:1040087440308:android:5e3b994c2c0a5a69caf0e1',
    messagingSenderId: '1040087440308',
    projectId: 'tuna-8c766',
    databaseURL: 'https://tuna-8c766-default-rtdb.firebaseio.com',
    storageBucket: 'tuna-8c766.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5uNzh5fMPxcWUAugdkNIkskVUHHCUa_k',
    appId: '1:1040087440308:ios:c67c54808f80408acaf0e1',
    messagingSenderId: '1040087440308',
    projectId: 'tuna-8c766',
    databaseURL: 'https://tuna-8c766-default-rtdb.firebaseio.com',
    storageBucket: 'tuna-8c766.appspot.com',
    iosClientId: '1040087440308-gqt82fcv17j3c46lfa5110m7mhsdpkat.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5uNzh5fMPxcWUAugdkNIkskVUHHCUa_k',
    appId: '1:1040087440308:ios:a35d287be5b696ffcaf0e1',
    messagingSenderId: '1040087440308',
    projectId: 'tuna-8c766',
    databaseURL: 'https://tuna-8c766-default-rtdb.firebaseio.com',
    storageBucket: 'tuna-8c766.appspot.com',
    iosClientId: '1040087440308-e700kps2okkn2t8qtjv0vujgim9jf3iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuna.RunnerTests',
  );
}
